bootstrapServers: localhost:9092
clientId: TestProducer

server:
  applicationConnectors:
  - type: http
    port: 9094
  adminConnectors:
  - type: http
    port: 9095

logging:
  level: INFO
  loggers:
    simpleapps.kafkapoc: DEBUG
