sudo: false
addons:
  apt:
    packages:
    - dblatex
    - dbtoepub
    - ditaa
    - doc-base
    - docbook
    - docbook-dsssl
    - docbook-utils
    - docbook-xml
    - docbook-xsl
    - docbook2odf
    - ghostscript
    - libbatik-java
    - pstoedit
    - python-pygments
notifications:
  email: false
script:
- "./examples/build all"
- export PATH=$PATH:./bin/asciitosvg/
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./bin/buildguide; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./bin/buildpdfs; fi
env:
  global:
    - secure: "IT/2HxHCMwKukSlkv9b2b9J+5YtSM1xmVW0K4eMbnbDICiFHYNXvaVxqzE/rQ7MGNgFiwnwixix+2nbBSOpB2ZqnUeGWdTsxtAuBm+FJ7aXRPZ6vr/q/5VhiXa21WB6U7hqTwAwrWZDhEZFoatAApWEhAj/q5399QzAxD+2Mi9M="
