package dsa.problemsolving.misc;

import java.sql.Timestamp;
import java.util.Calendar;

public class BruteForceStringMatch {
    public static void main(String[] args) {

        String text = "compares find a mismatch with the first character of the pattern. For "
                + "example, supposethat you search for the pattern pattern in the text of this "
                + "paragraph. There are 191characters up to the end of the first occurrence of the "
                + "pattern, only 7 of which are thecharacter p (and there are no occurrences of pa)"
                + ", so the total number of character compares is 191+7compares find a mismatch "
                + "with the first character of the pattern. For example, supposethat you search for"
                + " the pattern pattern in the text of this paragraph. There are 191characters up "
                + "to the end of the first occurrence of the pattern, only 7 of which are "
                + "thecharacter p (and there are no occurrences of pa), so the total number of "
                + "character compares is 191+7;compares find a mismatch with the first character of"
                + " the pattern. For example, supposethat you search for the pattern pattern in the"
                + " text of this paragraph. There are 191characters up to the end of the first "
                + "occurrence of the pattern, only 7 of which are thecharacter p (and there are no "
                + "occurrences of pa), so the total number of character compares is 191+7;compares "
                + "find a compares find a mismatch with the first character of the pattern. For "
                + "example, supposethat you search for the pattern pattern in the text of this "
                + "paragraph. There are 191characters up to the end of the first occurrence of the "
                + "pattern, only 7 of which are thecharacter p (and there are no occurrences of pa)"
                + ", so the total number of character compares is 191+7compares find a mismatch "
                + "with the first character of the pattern. For example, supposethat you search for"
                + " the pattern pattern in the text of this paragraph. There are 191characters up "
                + "to the end of the first occurrence of the pattern, only 7 of which are "
                + "thecharacter p (and there are no occurrences of pa), so the total number of "
                + "character compares is 191+7;compares find a mismatch with the first character of"
                + " the pattern. For example, supposethat you search for the pattern pattern in the"
                + " text of this paragraph. There are 191characters up to the end of the first "
                + "occurrence of the pattern, only 7 of which are thecharacter p (and there are no "
                + "occurrences of pa), so the total number of character compares is 191+7;compares "
                + "find a compares find a mismatch with the first character of the pattern. For "
                + "example, supposethat you search for the pattern pattern in the text of this "
                + "paragraph. There are 191characters up to the end of the first occurrence of the "
                + "pattern, only 7 of which are thecharacter p (and there are no occurrences of pa)"
                + ", so the total number of character compares is 191+7compares find a mismatch "
                + "with the first character of the pattern. For example, supposethat you search for"
                + " the pattern pattern in the text of this paragraph. There are 191characters up "
                + "to the end of the first occurrence of the pattern, only 7 of which are "
                + "thecharacter p (and there are no occurrences of pa), so the total number of "
                + "character compares is 191+7;compares find a mismatch with the first character of"
                + " the pattern. For example, supposethat you search for the pattern pattern in the"
                + " text of this paragraph. There are 191characters up to the end of the first "
                + "occurrence of the pattern, only 7 of which are thecharacter p (and there are no "
                + "occurrences of pa)ramsharma, so the total number of character compares is 191+7;"
                + "compares find a compares find a mismatch with the first character of the pattern"
                + ". For example, supposethat you search for the pattern pattern in the text of "
                + "this paragraph. There are 191characters up to the end of the first occurrence of"
                + " the pattern, only 7 of which are thecharacter p (and there are no occurrences "
                + "of pa), so the total number of character compares is 191+7compares find a "
                + "mismatch with the first character of the pattern. For example, supposethat you "
                + "search for the pattern pattern in the text of this paragraph. There are "
                + "191characters up to the end of the first occurrence of the pattern, only 7 of "
                + "which are thecharacter p (and there are no occurrences of pa), so the total "
                + "number of character compares is 191+7;compares find a mismatch with the first "
                + "character of the pattern. For example, supposethat you search for the pattern "
                + "pattern in the text of this paragraph. There are 191characters up to the end of "
                + "the first occurrence of the pattern, only 7 of which are thecharacter p (and "
                + "there are no occurrences of pa), so the total number of character compares is "
                + "191+7;compares find a compares find a mismatch with the first character of the "
                + "pattern. For example, supposethat you search for the pattern pattern in the text"
                + " of this paragraph. There are 191characters up to the end of the first "
                + "occurrence of the pattern, only 7 of which are thecharacter p (and there are no "
                + "occurrences of pa), so the total number of character compares is 191+7compares "
                + "find a mismatch with the first character of the pattern. For example, "
                + "supposethat you search for the pattern pattern in the text of this paragraph. "
                + "There are 191characters up to the end of the first occurrence of the pattern, "
                + "only 7 of which are thecharacter p (and there are no occurrences of pa), so the "
                + "total number of character compares is 191+7;compares find a mismatch with the "
                + "first character of the pattern. For example, supposethat you search for the "
                + "pattern pattern in the text of this paragraph. There are 191characters up to the"
                + " end of the first occurrence of the pattern, only 7 of which are thecharacter p "
                + "(and there are no occurrences of pa), so the total number of character compares "
                + "is 191+7;compares find a compares find a mismatch with the first character of "
                + "the pattern. For example, supposethat you search for the pattern pattern in the "
                + "text of this paragraph. There are 191characters up to the end of the first "
                + "occurrence of the pattern, only 7 of which are thecharacter p (and there are no "
                + "occurrences of pa), so the total number of character compares is 191+7compares "
                + "find a mismatch with the first character of the pattern. For example, "
                + "supposethat you search for the pattern pattern in the text of this paragraph. "
                + "There are 191characters up to the end of the first occurrence of the pattern, "
                + "only 7 of which are thecharacter p (and there are no occurrences of pa), so the "
                + "total number of character compares is 191+7;compares find a mismatch with the "
                + "first character of the pattern. For example, supposethat you search for the "
                + "pattern pattern in the text of this paragraph. There are 191characters up to the"
                + " end of the first occurrence of the pattern, only 7 of which are thecharacter p "
                + "(and there are no occurrences of pa)ramsharma, so the total number of character "
                + "compares is 191+7;compares find a compares find a mismatch with the first "
                + "character of the pattern. For example, supposethat you search for the pattern "
                + "pattern in the text of this paragraph. There are 191characters up to the end of "
                + "the first occurrence of the pattern, only 7 of which are thecharacter p (and "
                + "there are no occurrences of pa), so the total number of character compares is "
                + "191+7compares find a mismatch with the first character of the pattern. For "
                + "example, supposethat you search for the pattern pattern in the text of this "
                + "paragraph. There are 191characters up to the end of the first occurrence of the "
                + "pattern, only 7 of which are thecharacter p (and there are no occurrences of pa)"
                + ", so the total number of character compares is 191+7;compares find a mismatch "
                + "with the first character of the pattern. For example, supposethat you search for"
                + " the pattern pattern in the text of this paragraph. There are 191characters up "
                + "to the end of the first occurrence of the pattern, only 7 of which are "
                + "thecharacter p (and there are no occurrences of pa), so the total number of "
                + "character compares is 191+7;compares find a compares find a mismatch with the "
                + "first character of the pattern. For example, supposethat you search for the "
                + "pattern pattern in the text of this paragraph. There are 191characters up to the"
                + " end of the first occurrence of the pattern, only 7 of which are thecharacter p "
                + "(and there are no occurrences of pa), so the total number of character compares "
                + "is 191+7compares find a mismatch with the first character of the pattern. For "
                + "example, supposethat you search for the pattern pattern in the text of this "
                + "paragraph. There are 191characters up to the end of the first occurrence of the "
                + "pattern, only 7 of which are thecharacter p (and there are no occurrences of pa)"
                + ", so the total number of character compares is 191+7;compares find a mismatch "
                + "with the first character of the pattern. For example, supposethat you search for"
                + " the pattern pattern in the text of this paragraph. There are 191characters up "
                + "to the end of the first occurrence of the pattern, only 7 of which are "
                + "thecharacter p (and there are no occurrences of pa), so the total number of "
                + "character compares is 191+7;compares find a compares find a mismatch with the "
                + "first character of the pattern. For example, supposethat you search for the "
                + "pattern pattern in the text of this paragraph. There are 191characters up to the"
                + " end of the first occurrence of the pattern, only 7 of which are thecharacter p "
                + "(and there are no occurrences of pa), so the total number of character compares "
                + "is 191+7compares find a mismatch with the first character of the pattern. For "
                + "example, supposethat you search for the pattern pattern in the text of this "
                + "paragraph. There are 191characters up to the end of the first occurrence of the "
                + "pattern, only 7 of which are thecharacter p (and there are no occurrences of pa)"
                + ", so the total number of character compares is 191+7;compares find a mismatch "
                + "with the first character of the pattern. For example, supposethat you search for"
                + " the pattern pattern in the text of this paragraph. There are 191characters up "
                + "to the end of the first occurrence of the pattern, only 7 of which are "
                + "thecharacter p (and there are no occurrences of pa)ramsharma, so the total "
                + "number of character compares is 191+7;compares find a compares find a mismatch "
                + "with the first character of the pattern. For example, supposethat you search for"
                + " the pattern pattern in the text of this paragraph. There are 191characters up "
                + "to the end of the first occurrence of the pattern, only 7 of which are "
                + "thecharacter p (and there are no occurrences of pa), so the total number of "
                + "character compares is 191+7compares find a mismatch with the first character of "
                + "the pattern. For example, supposethat you search for the pattern pattern in the "
                + "text of this paragraph. There are 191characters up to the end of the first "
                + "occurrence of the pattern, only 7 of which are thecharacter p (and there are no "
                + "occurrences of pa), so the total number of character compares is 191+7;compares "
                + "find a mismatch with the first character of the pattern. For example, "
                + "supposethat you search for the pattern pattern in the text of this paragraph. "
                + "There are 191characters up to the end of the first occurrence of the pattern, "
                + "only 7 of which are thecharacter p (and there are no occurrences of pa), so the "
                + "total number of character compares is 191+7;compares find a compares find a "
                + "mismatch with the first character of the pattern. For example, supposethat you "
                + "search for the pattern pattern in the text of this paragraph. There are "
                + "191characters up to the end of the first occurrence of the pattern, only 7 of "
                + "which are thecharacter p (and there are no occurrences of pa), so the total "
                + "number of character compares is 191+7compares find a mismatch with the first "
                + "character of the pattern. For example, supposethat you search for the pattern "
                + "pattern in the text of this paragraph. There are 191characters up to the end of "
                + "the first occurrence of the pattern, only 7 of which are thecharacter p (and "
                + "there are no occurrences of pa), so the total number of character compares is "
                + "191+7;compares find a mismatch with the first character of the pattern. For "
                + "example, supposethat you search for the pattern pattern in the text of this "
                + "paragraph. There are 191characters up to the end of the first occurrence of the "
                + "pattern, only 7 of which are thecharacter p (and there are no occurrences of pa)"
                + ", so the total number of character compares is 191+7;compares find a compares "
                + "find a mismatch with the first character of the pattern. For example, "
                + "supposethat you search for the pattern pattern in the text of this paragraph. "
                + "There are 191characters up to the end of the first occurrence of the pattern, "
                + "only 7 of which are thecharacter p (and there are no occurrences of pa), so the "
                + "total number of character compares is 191+7compares find a mismatch with the "
                + "first character of the pattern. For example, supposethat you search for the "
                + "pattern pattern in the text of this paragraph. There are 191characters up to the"
                + " end of the first occurrence of the pattern, only 7 of which are thecharacter p "
                + "(and there are no occurrences of pa), so the total number of character compares "
                + "is 191+7;compares find a mismatch with the first character of the pattern. For "
                + "example, supposethat you search for the pattern pattern in the text of this "
                + "paragraph. There are 191characters up to the end of the first occurrence of the "
                + "pattern, only 789rsh of which are thecharacter p (and there are no occurrences "
                + "of pa)ramsharma, so the total number of character compares is 191+7;compares "
                + "find a "
                + "compares find a mismatch with the first character of the pattern. For "
                + "example, supposethat you search for the pattern pattern in the text of this "
                + "paragraph. There are 191characters up to the end of the first occurrence of the "
                + "pattern, only 7 of which are thecharacter p (and there are no occurrences of pa)"
                + ", so the total number of character compares is 191+7compares find a mismatch "
                + "with the first character of the pattern. For example, supposethat you search for"
                + " the pattern pattern in the text of this paragraph. There are 191characters up "
                + "to the end of the first occurrence of the pattern, only 7 of which are "
                + "thecharacter p (and there are no occurrences of pa), so the total number of "
                + "character compares is 191+7;compares find a mismatch with the first character of"
                + " the pattern. For example, supposethat you search for the pattern pattern in the"
                + " text of this paragraph. There are 191characters up to the end of the first "
                + "occurrence of the pattern, only 7 of which are thecharacter p (and there are no "
                + "occurrences of pa), so the total number of character compares is 191+7;compares "
                + "find a compares find a mismatch with the first character of the pattern. For "
                + "example, supposethat you search for the pattern pattern in the text of this "
                + "paragraph. There are 191characters up to the end of the first occurrence of the "
                + "pattern, only 7 of which are thecharacter p (and there are no occurrences of pa)"
                + ", so the total number of character compares is 191+7compares find a mismatch "
                + "with the first character of the pattern. For example, supposethat you search for"
                + " the pattern pattern in the text of this paragraph. There are 191characters up "
                + "to the end of the first occurrence of the pattern, only 7 of which are "
                + "thecharacter p (and there are no occurrences of pa), so the total number of "
                + "character compares is 191+7;compares find a mismatch with the first character of"
                + " the pattern. For example, supposethat you search for the pattern pattern in the"
                + " text of this paragraph. There are 191characters up to the end of the first "
                + "occurrence of the pattern, only 7 of which are thecharacter p (and there are no "
                + "occurrences of pa), so the total number of character compares is 191+7;compares "
                + "find a compares find a mismatch with the first character of the pattern. For "
                + "example, supposethat you search for the pattern pattern in the text of this "
                + "paragraph. There are 191characters up to the end of the first occurrence of the "
                + "pattern, only 7 of which are thecharacter p (and there are no occurrences of pa)"
                + ", so the total number of character compares is 191+7compares find a mismatch "
                + "with the first character of the pattern. For example, supposethat you search for"
                + " the pattern pattern in the text of this paragraph. There are 191characters up "
                + "to the end of the first occurrence of the pattern, only 7 of which are "
                + "thecharacter p (and there are no occurrences of pa), so the total number of "
                + "character compares is 191+7;compares find a mismatch with the first character of"
                + " the pattern. For example, supposethat you search for the pattern pattern in the"
                + " text of this paragraph. There are 191characters up to the end of the first "
                + "occurrence of the pattern, only 7 of which are thecharacter p (and there are no "
                + "occurrences of pa)ramsharma, so the total number of character compares is 191+7;"
                + "compares find a compares find a mismatch with the first character of the pattern"
                + ". For example, supposethat you search for the pattern pattern in the text of "
                + "this paragraph. There are 191characters up to the end of the first occurrence of"
                + " the pattern, only 7 of which are thecharacter p (and there are no occurrences "
                + "of pa), so the total number of character compares is 191+7compares find a "
                + "mismatch with the first character of the pattern. For example, supposethat you "
                + "search for the pattern pattern in the text of this paragraph. There are "
                + "191characters up to the end of the first occurrence of the pattern, only 7 of "
                + "which are thecharacter p (and there are no occurrences of pa), so the total "
                + "number of character compares is 191+7;compares find a mismatch with the first "
                + "character of the pattern. For example, supposethat you search for the pattern "
                + "pattern in the text of this paragraph. There are 191characters up to the end of "
                + "the first occurrence of the pattern, only 7 of which are thecharacter p (and "
                + "there are no occurrences of pa), so the total number of character compares is "
                + "191+7;compares find a compares find a mismatch with the first character of the "
                + "pattern. For example, supposethat you search for the pattern pattern in the text"
                + " of this paragraph. There are 191characters up to the end of the first "
                + "occurrence of the pattern, only 7 of which are thecharacter p (and there are no "
                + "occurrences of pa), so the total number of character compares is 191+7compares "
                + "find a mismatch with the first character of the pattern. For example, "
                + "supposethat you search for the pattern pattern in the text of this paragraph. "
                + "There are 191characters up to the end of the first occurrence of the pattern, "
                + "only 7 of which are thecharacter p (and there are no occurrences of pa), so the "
                + "total number of character compares is 191+7;compares find a mismatch with the "
                + "first character of the pattern. For example, supposethat you search for the "
                + "pattern pattern in the text of this paragraph. There are 191characters up to the"
                + " end of the first occurrence of the pattern, only 7 of which are thecharacter p "
                + "(and there are no occurrences of pa), so the total number of character compares "
                + "is 191+7;compares find a compares find a mismatch with the first character of "
                + "the pattern. For example, supposethat you search for the pattern pattern in the "
                + "text of this paragraph. There are 191characters up to the end of the first "
                + "occurrence of the pattern, only 7 of which are thecharacter p (and there are no "
                + "occurrences of pa), so the total number of character compares is 191+7compares "
                + "find a mismatch with the first character of the pattern. For example, "
                + "supposethat you search for the pattern pattern in the text of this paragraph. "
                + "There are 191characters up to the end of the first occurrence of the pattern, "
                + "only 7 of which are thecharacter p (and there are no occurrences of pa), so the "
                + "total number of character compares is 191+7;compares find a mismatch with the "
                + "first character of the pattern. For example, supposethat you search for the "
                + "pattern pattern in the text of this paragraph. There are 191characters up to the"
                + " end of the first occurrence of the pattern, only 7 of which are thecharacter p "
                + "(and there are no occurrences of pa)ramsharma, so the total number of character "
                + "compares is 191+7;compares find a compares find a mismatch with the first "
                + "character of the pattern. For example, supposethat you search for the pattern "
                + "pattern in the text of this paragraph. There are 191characters up to the end of "
                + "the first occurrence of the pattern, only 7 of which are thecharacter p (and "
                + "there are no occurrences of pa), so the total number of character compares is "
                + "191+7compares find a mismatch with the first character of the pattern. For "
                + "example, supposethat you search for the pattern pattern in the text of this "
                + "paragraph. There are 191characters up to the end of the first occurrence of the "
                + "pattern, only 7 of which are thecharacter p (and there are no occurrences of pa)"
                + ", so the total number of character compares is 191+7;compares find a mismatch "
                + "with the first character of the pattern. For example, supposethat you search for"
                + " the pattern pattern in the text of this paragraph. There are 191characters up "
                + "to the end of the first occurrence of the pattern, only 7 of which are "
                + "thecharacter p (and there are no occurrences of pa), so the total number of "
                + "character compares is 191+7;compares find a compares find a mismatch with the "
                + "first character of the pattern. For example, supposethat you search for the "
                + "pattern pattern in the text of this paragraph. There are 191characters up to the"
                + " end of the first occurrence of the pattern, only 7 of which are thecharacter p "
                + "(and there are no occurrences of pa), so the total number of character compares "
                + "is 191+7compares find a mismatch with the first character of the pattern. For "
                + "example, supposethat you search for the pattern pattern in the text of this "
                + "paragraph. There are 191characters up to the end of the first occurrence of the "
                + "pattern, only 7 of which are thecharacter p (and there are no occurrences of pa)"
                + ", so the total number of character compares is 191+7;compares find a mismatch "
                + "with the first character of the pattern. For example, supposethat you search for"
                + " the pattern pattern in the text of this paragraph. There are 191characters up "
                + "to the end of the first occurrence of the pattern, only 7 of which are "
                + "thecharacter p (and there are no occurrences of pa), so the total number of "
                + "character compares is 191+7;compares find a compares find a mismatch with the "
                + "first character of the pattern. For example, supposethat you search for the "
                + "pattern pattern in the text of this paragraph. There are 191characters up to the"
                + " end of the first occurrence of the pattern, only 7 of which are thecharacter p "
                + "(and there are no occurrences of pa), so the total number of character compares "
                + "is 191+7compares find a mismatch with the first character of the pattern. For "
                + "example, supposethat you search for the pattern pattern in the text of this "
                + "paragraph. There are 191characters up to the end of the first occurrence of the "
                + "pattern, only 7 of which are thecharacter p (and there are no occurrences of pa)"
                + ", so the total number of character compares is 191+7;compares find a mismatch "
                + "with the first character of the pattern. For example, supposethat you search for"
                + " the pattern pattern in the text of this paragraph. There are 191characters up "
                + "to the end of the first occurrence of the pattern, only 7 of which are "
                + "thecharacter p (and there are no occurrences of pa)ramsharma, so the total "
                + "number of character compares is 191+7;compares find a compares find a mismatch "
                + "with the first character of the pattern. For example, supposethat you search for"
                + " the pattern pattern in the text of this paragraph. There are 191characters up "
                + "to the end of the first occurrence of the pattern, only 7 of which are "
                + "thecharacter p (and there are no occurrences of pa), so the total number of "
                + "character compares is 191+7compares find a mismatch with the first character of "
                + "the pattern. For example, supposethat you search for the pattern pattern in the "
                + "text of this paragraph. There are 191characters up to the end of the first "
                + "occurrence of the pattern, only 7 of which are thecharacter p (and there are no "
                + "occurrences of pa), so the total number of character compares is 191+7;compares "
                + "find a mismatch with the first character of the pattern. For example, "
                + "supposethat you search for the pattern pattern in the text of this paragraph. "
                + "There are 191characters up to the end of the first occurrence of the pattern, "
                + "only 7 of which are thecharacter p (and there are no occurrences of pa), so the "
                + "total number of character compares is 191+7;compares find a compares find a "
                + "mismatch with the first character of the pattern. For example, supposethat you "
                + "search for the pattern pattern in the text of this paragraph. There are "
                + "191characters up to the end of the first occurrence of the pattern, only 7 of "
                + "which are thecharacter p (and there are no occurrences of pa), so the total "
                + "number of character compares is 191+7compares find a mismatch with the first "
                + "character of the pattern. For example, supposethat you search for the pattern "
                + "pattern in the text of this paragraph. There are 191characters up to the end of "
                + "the first occurrence of the pattern, only 7 of which are thecharacter p (and "
                + "there are no occurrences of pa), so the total number of character compares is "
                + "191+7;compares find a mismatch with the first character of the pattern. For "
                + "example, supposethat you search for the pattern pattern in the text of this "
                + "paragraph. There are 191characters up to the end of the first occurrence of the "
                + "pattern, only 7 of which are thecharacter p (and there are no occurrences of pa)"
                + ", so the total number of character compares is 191+7;compares find a compares "
                + "find a mismatch with the first character of the pattern. For example, "
                + "supposethat you search for the pattern pattern in the text of this paragraph. "
                + "There are 191characters up to the end of the first occurrence of the pattern, "
                + "only 7 of which are thecharacter p (and there are no occurrences of pa), so the "
                + "total number of character compares is 191+7compares find a mismatch with the "
                + "first character of the pattern. For example, supposethat you search for the "
                + "pattern pattern in the text of this paragraph. There are 191characters up to the"
                + " end of the first occurrence of the pattern, only 7 of which are thecharacter p "
                + "(and there are no occurrences of pa), so the total number of character compares "
                + "is 191+7;compares find a mismatch with the first character of the pattern. For "
                + "example, supposethat you search for the pattern pattern in the text of this "
                + "paragraph. There are 191characters up to the end of the first occurrence of the "
                + "pattern, only 789rsh of which are thecharacter p (and there are no occurrences "
                + "of pa)ramsharma, so the total number of character compares is 191+793;compares "
                + "xxx";
        String pattern = "191+793;compares";
        System.out.println(findPattern(text, pattern));
    }

    private static boolean findPattern(String text, String pattern) {
        Timestamp start = new Timestamp(Calendar.getInstance().getTimeInMillis());
        System.out.println(start);

        for (int i = 0; i < (text.length() - pattern.length()); i++) {
            for (int j = 0; j < pattern.length(); j++) {
                if (text.charAt(i + j) != pattern.charAt(j)) {
                    break;
                }
                if (j == (pattern.length() - 1)) {
                    Timestamp whenFound = new Timestamp(Calendar.getInstance().getTimeInMillis());
                    System.out.println(whenFound);
                    return true;
                }
            }
        }
        Timestamp whenFound = new Timestamp(Calendar.getInstance().getTimeInMillis());
        System.out.println(whenFound);
        return false;
    }
}
